// --- MODEL PEMBELAJARAN & ASPEK MURID MAP ---
export const MODEL_PEMBELAJARAN = {
    "Problem-Based Learning (PBL)": { memahami: "Orientasi Masalah: Murid disajikan sebuah kasus nyata terkait topik. Murid merumuskan pertanyaan esensialnya.", mengaplikasi: "Investigasi: Murid melakukan penyelidikan kelompok, mengumpulkan data, dan mendiskusikan berbagai alternatif solusi nyata.", merefleksi: "Evaluasi: Murid menyajikan solusi akhir yang disepakati dan mengevaluasi efektivitas pemecahan masalah bersama guru.", sumatif: "Penilaian Unjuk Kerja & Laporan Analisis Pemecahan Masalah." },
    "Project-Based Learning (PjBL)": { memahami: "Pertanyaan Mendasar: Murid mengamati masalah kontekstual terkait topik dan mendiskusikan rencana proyek penyelesaian nyata.", mengaplikasi: "Desain & Pelaksanaan: Murid secara kolaboratif merancang jadwal, membagi tugas, dan mulai membuat prototipe/karya nyata.", merefleksi: "Uji Hasil: Murid mempresentasikan hasil karya, melakukan uji coba produk, dan menerima masukan kelompok lain.", sumatif: "Penilaian Produk/Proyek Nyata (Kriteria: Orisinalitas, Fungsi, Estetika)." },
    "Discovery Learning": { memahami: "Stimulasi: Murid mengeksplorasi berbagai contoh dan fenomena dari konsep topik materi yang disajikan oleh guru.", mengaplikasi: "Pengolahan Data: Murid membandingkan informasi, mengidentifikasi pola, dan membuktikan rumusan konsep melalui observasi terarah.", merefleksi: "Generalisasi: Murid menarik kesimpulan umum tentang sifat, rumus, atau aturan utama dari topik materi.", sumatif: "Tes Tertulis / Uraian Pemahaman Konsep Kompleks." },
    "Inquiry Learning": { memahami: "Rumusan Masalah: Guru mendemonstrasikan sebuah fenomena terkait topik. Murid merumuskan hipotesis ilmiah sementara.", mengaplikasi: "Eksperimen: Murid merancang eksperimen sederhana, mengumpulkan bukti fisik, dan mencatat data hasil pengamatan kelompok.", merefleksi: "Pembuktian: Murid menganalisis data untuk membuktikan kebenaran hipotesis dan mengomunikasikan temuan ilmiahnya.", sumatif: "Laporan Praktikum / Eksperimen Sistematis." },
    "Jigsaw": { memahami: `Grup Ahli: Murid dibagi ke dalam kelompok dan setiap anggota menjadi "ahli" untuk satu sub-materi spesifik.`, mengaplikasi: `Diskusi Silang: Kelompok ahli berdiskusi mendalam, lalu murid kembali ke kelompok asal untuk saling mengajarkan sub-materi ke temannya.`, merefleksi: `Sintesis: Murid menyatukan semua kepingan informasi menjadi satu pemahaman utuh mengenai topik.`, sumatif: `Kuis Individu komprehensif tentang keseluruhan materi.` },
    "STAD": { memahami: `Penyajian: Guru menyajikan materi dasar tentang topik secara klasikal.`, mengaplikasi: `Kerja Tim: Murid belajar dalam kelompok heterogen untuk memastikan semua anggota benar-benar memahami (tutor sebaya).`, merefleksi: `Rekognisi: Diadakan kuis individu yang nilainya disumbangkan untuk skor tim. Kelompok terbaik diberikan penghargaan.`, sumatif: `Kuis Individu dengan sistem skor kontribusi kelompok.` },
    "TGT (Teams Games Tournament)": { memahami: `Orientasi: Pengenalan konsep secara interaktif.`, mengaplikasi: `Persiapan Turnamen: Kelompok belajar bersama untuk mempersiapkan anggota tim menghadapi turnamen akademik terkait topik.`, merefleksi: `Turnamen: Perwakilan kelompok berlomba menjawab soal-soal permainan akademik untuk mengumpulkan poin.`, sumatif: `Skor Turnamen Akademik antar kelompok.` },
    "TPS (Think-Pair-Share)": { memahami: `Think: Guru melempar pertanyaan kompleks tentang topik. Murid diberikan waktu memikirkan jawabannya secara mandiri.`, mengaplikasi: `Pair: Murid berdiskusi dengan rekan sebangku (berpasangan) untuk menyatukan dan menyempurnakan jawaban.`, merefleksi: `Share: Pasangan murid membagikan hasil pemikiran mereka ke seluruh kelas untuk ditanggapi.`, sumatif: `Penugasan Esai Pendek / Tanggapan Tertulis.` },
    "NHT (Numbered Heads Together)": { memahami: `Penomoran: Setiap murid dalam kelompok diberi nomor. Guru mengajukan persoalan tentang topik.`, mengaplikasi: `Heads Together: Kelompok menyatukan kepala berdiskusi memastikan setiap nomor paham jawaban dari masalah.`, merefleksi: `Pemanggilan: Guru memanggil satu nomor acak. Murid dengan nomor tersebut wajib menjawab mewakili kelompoknya.`, sumatif: `Penilaian Partisipasi dan Ketepatan Jawaban Acak.` },
    "CTL (Contextual Teaching and Learning)": { memahami: `Constructivism: Mengaitkan materi topik dengan pengalaman dan situasi dunia nyata yang dialami murid.`, mengaplikasi: `Learning Community: Murid melakukan inkuiri dan bekerja sama memecahkan masalah keseharian terkait materi.`, merefleksi: `Authentic Assessment: Murid melakukan refleksi atas apa yang dipelajari dan memamerkan hasil kerjanya secara otentik.`, sumatif: `Penilaian Portofolio & Rubrik Otentik keseharian.` },
    "RME (Realistic Mathematics/Science Education)": { memahami: `Masalah Realistis: Memulai pembelajaran dengan masalah/cerita kontekstual terkait topik yang bisa dibayangkan siswa.`, mengaplikasi: `Matematisasi: Murid mengubah masalah nyata tersebut ke dalam bahasa simbolik/rumus (matematisasi).`, merefleksi: `Interaktivitas: Membandingkan dan mendiskusikan berbagai cara/strategi penyelesaian masalah yang ditemukan.`, sumatif: `Tes Pemecahan Masalah Realistis (Problem Solving).` },
    "Flipped Classroom": { memahami: `Pra-Kelas: Review materi dasar topik yang telah dipelajari murid secara mandiri di rumah sebelumnya (via modul/video).`, mengaplikasi: `Aktivitas Kelas: Jam kelas difokuskan penuh untuk praktik, tugas kelompok, dan diskusi mendalam memecahkan tantangan.`, merefleksi: `Penguatan: Guru memberikan umpan balik langsung atas kesulitan tingkat tinggi yang dihadapi murid saat praktik di kelas.`, sumatif: `Penilaian Praktik / Tugas Pendalaman di Kelas.` },
    "Blended / Hybrid Learning": { memahami: `Eksplorasi Daring: Murid memaparkan hasil penelusuran materi topik yang telah dilakukan secara online.`, mengaplikasi: `Kolaborasi Luring: Aktivitas tatap muka difokuskan untuk eksperimen/kolaborasi fisik yang tidak bisa dilakukan online.`, merefleksi: `Sinkronisasi: Menggabungkan pengalaman belajar online dan offline menjadi satu kesimpulan utuh.`, sumatif: `Kuis Online (LMS) Terintegrasi Proyek/Aktivitas Kelas.` },
    "Game-Based Learning": { memahami: `Aturan Main: Pengenalan mekanika permainan/simulasi digital yang memuat tujuan pembelajaran tentang topik.`, mengaplikasi: `Bermain/Simulasi: Murid menyelesaikan misi atau tantangan di dalam lingkungan game yang merepresentasikan konsep.`, merefleksi: `Debriefing: Diskusi menarik makna/konsep ilmiah dari pengalaman bermain game ke dunia nyata.`, sumatif: `Pencapaian Misi (Score/Badge) & Refleksi Tertulis.` },
    "Self-Directed Learning": { memahami: `Diagnosis: Murid mengidentifikasi secara mandiri apa yang belum ia kuasai mengenai topik.`, mengaplikasi: `Strategi Mandiri: Murid merumuskan tujuan, memilih sumber belajar, dan mengeksekusi rencana belajarnya.`, merefleksi: `Evaluasi Diri: Murid mengevaluasi hasil belajarnya sendiri dan menyusun rencana tindak lanjut.`, sumatif: `Jurnal Belajar Mandiri (Learning Log) & Kontrak Belajar.` },
    "Direct Instruction": { memahami: `Demonstrasi: Guru menyampaikan tujuan dan mendemonstrasikan secara langsung prosedur/langkah-langkah materi.`, mengaplikasi: `Latihan Terbimbing: Murid meniru atau mempraktikkan keterampilan dasar dengan bimbingan dan koreksi guru.`, merefleksi: `Latihan Mandiri: Murid melakukan praktik secara mandiri untuk memantapkan penguasaan prosedural.`, sumatif: `Tes Praktik / Keterampilan Prosedural.` },
    "Mastery Learning": { memahami: `Penyajian Blok: Materi topik disajikan dalam unit-unit kecil yang sangat terstruktur.`, mengaplikasi: `Latihan & Remedial: Murid berlatih. Yang belum tuntas diberikan remedial instan, yang sudah tuntas diberikan pengayaan.`, merefleksi: `Ketuntasan: Memastikan seluruh murid mencapai standar ketuntasan minimal sebelum berpindah ke unit berikutnya.`, sumatif: `Tes Formatif/Sumatif Berulang hingga Mencapai Ketuntasan.` },
    "TGfU (Teaching Games for Understanding)": { memahami: `Apresiasi Game: Murid diperkenalkan pada permainan taktis sederhana yang memuat elemen konsep.`, mengaplikasi: `Kesadaran Taktis: Murid memodifikasi atau membuat keputusan taktis secara langsung di lapangan terkait penyelesaian masalah.`, merefleksi: `Eksekusi Keterampilan: Mengidentifikasi keterampilan/teknik spesifik apa yang perlu diperbaiki untuk meningkatkan performa.`, sumatif: `Penilaian Kinerja Taktis (Tactical Performance).` },
    "STEM (Engineering Design Process)": {
        memahami: "Ask: Murid mengidentifikasi masalah nyata, batasan teknis (constraints), serta kriteria keberhasilan proyek STEM.",
        mengaplikasi: "Imagine, Plan, & Create: Murid curah gagasan solusi, merancang blueprint sketsa fisik/teknis, dan membangun purwarupa (prototype) proyek.",
        merefleksi: "Test & Improve: Murid menguji coba purwarupa, mengumpulkan data hasil pengukuran kuantitatif, dan melakukan iterasi perbaikan desain.",
        sumatif: "Penilaian Proses Rancang (Engineering Design Process) & Evaluasi Keberhasilan Produk/Purwarupa."
    }
};

export const getModelData = (metode) => MODEL_PEMBELAJARAN[metode] || MODEL_PEMBELAJARAN["Problem-Based Learning (PBL)"];

export const ASPEK_MURID_MAP = {
    "Disiplin Positif": "1. Tanggung jawab terhadap konsekuensi tindakan.\n2. Kemampuan refleksi diri dan kontrol emosi.",
    "Keteraturan Suasana Kelas": "1. Kepatuhan pada kesepakatan belajar kelas.\n2. Tingkat partisipasi aktif kolaboratif kelompok.",
    "Umpan Balik Konstruktif": "1. Keterbukaan menerima masukan perbaikan dari teman/guru.\n2. Kemampuan memberikan feedback objektif.",
    "Perhatian dan Kepedulian": "1. Sikap empati membantu rekan yang kesulitan.\n2. Rasa percaya diri dalam memaparkan opini.",
    "Ekspektasi pada Peserta Didik": "1. Kegigihan (Grit) menyelesaikan tugas menantang.\n2. Kemandirian pengerjaan target indikator.",
    "Aktivitas Interaktif": "1. Keaktifan berpendapat dalam forum diskusi.\n2. Menghargai perbedaan argumen rekan.",
    "Instruksi yang Adaptif": "1. Respon terhadap variasi tingkat kesulitan tugas.\n2. Kedisiplinan melakukan evaluasi berkala.",
    "Instruksi Pembelajaran": "1. Pemahaman runtut alur prosedural instruksi.\n2. Ketepatan aplikasi contoh kontekstual materi."
};
